### ISSUE TITLE
On build "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by jthake** [OfficeDev/Office-Add-in-Calculator#1]
When cloning and building. I get this error

1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\SharePointTools\Microsoft.VisualStudio.SharePoint.targets(399,5): error : Object reference not set to an instance of an object.

I am using Windows 10, Visual Studio 2015 (Office tools checked on install) and Office 2016. 
I don't quite understand why it is using SharePoint.targets?

Other projects are working just fine.

**Comment by mimisasouvanh** [comment]
Not sure why. Let me test it on another machine. It could be that the solution file wasn't built properly. Could you try creating a new Add-in:
1. In Visual Studio, open a new project for an App for Office.
2. Copy the Home.js and Home.html into your ../App/Home folder.
3. Copy App.html into your ../App folder
You don't need to copy the manifest file over. VS will create one for you.

**Comment by mimisasouvanh** [comment]
@jthake Please try it now. I've fixed some issues with the call to the CDN files in home.html.

**Comment by jthake** [comment]
Thank you, that works now.
